version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    env_file:
      - .env
    ports:
      - '5433:5432'
    network_mode: host

  manuscript-api:
    container_name: manuscript-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - '8282:5000'
    restart: always
    network_mode: host
    # command: >
    #   sh -c "
    #   npx prisma migrate deploy &&
    #   yarn start:prod
    #   "
